# 1. Introduction

## 1.1 Dataset Overview

This dataset contains daily reports related to the humanitarian impact of the Gaza conflict that began on October 7, 2023. The data was obtained from the Tech for Palestine open-data platform and covers the period from October 7, 2023, to May 30, 2026.

The dataset includes a wide range of indicators related to the conflict, such as reported deaths, injuries, aid-seeker casualties, famine-related deaths, and casualties among specific professional groups including journalists, medical personnel, and civil defense workers. In addition, it contains information about infrastructure damage, including residential buildings, educational facilities, civic buildings, and places of worship.

Each record represents a reporting period and includes both official and extrapolated values, allowing the dataset to provide a continuous daily time series of humanitarian indicators throughout the conflict.

## 1.2 Data Source

The dataset used in this analysis was obtained from the Tech for Palestine open-data platform. The platform aggregates and publishes humanitarian indicators related to the Gaza conflict from official reporting sources. The dataset is available in multiple formats, including JSON, CSV, and API endpoints, making it accessible for data analysis and visualization tasks.

According to the dataset documentation, the data is updated regularly as new reports become available. The dataset includes information collected from multiple official sources and provides both reported and extrapolated values to maintain a continuous daily time series.

## 1.3 Project Objective

The objective of this project is to explore and understand the humanitarian impact reflected in the Gaza conflict dataset. Through data wrangling and exploratory data analysis, this project aims to examine trends, patterns, and relationships among reported casualties, injuries, humanitarian indicators, and infrastructure damage.

In addition to exploring the data itself, this project also seeks to assess data quality, identify potential limitations, and better understand the structure and reporting methodology used within the dataset. The findings will be summarized through visualizations and analytical observations to provide a clearer understanding of the reported indicators over time.

## 1.4 Analysis Questions

The following questions will guide the exploratory analysis of this dataset:

* Which periods experienced the highest numbers of reported deaths and injuries throughout the conflict?
* When did famine-related deaths begin to appear, and how did they evolve over time?
* Is there a temporal relationship between famine-related deaths and casualties among people seeking humanitarian aid?
* How has the destruction and damage of educational facilities evolved throughout the reporting period?
* What is the difference between the number of educational buildings reported as destroyed and those reported as damaged?
* Which category of infrastructure experienced the greatest level of destruction during the conflict?
* How have casualties among journalists, medical personnel, and civil defense workers changed over time?
* During which periods was the destruction of places of worship, particularly mosques, most significant?
* Are there observable relationships between casualty indicators and infrastructure damage indicators?
* How do official reported values compare with extrapolated values throughout the dataset?

# 2. Data Wrangling

## 2.1 Gather

The dataset used in this project was obtained from the Tech for Palestine open-data platform. The platform provides publicly accessible humanitarian datasets related to the Gaza conflict through downloadable files and API endpoints.

For this analysis, the data was retrieved from the official API and loaded into a pandas DataFrame for further processing. The original data was provided in JSON format and subsequently prepared for assessment and cleaning.

Source: https://data.techforpalestine.org/

Data Format: JSON (API Response)

Collection Method: API Retrieval

Time Coverage: October 7, 2023 – May 30, 2026

# 2.2 Assess

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv('Gaza Casualties and Infrastructure Damage Dataset.csv')
df.head()

,report_date,report_source,report_period,ext_massacres_cum,killed,killed_cum,ext_killed,ext_killed_cum,ext_killed_children_cum,ext_killed_women_cum,...,places_of_worship.ext_mosques_damaged,places_of_worship.ext_churches_destroyed,residential.ext_destroyed,residential.destroyed,civic_buildings.destroyed,educational_buildings.destroyed,educational_buildings.damaged,places_of_worship.mosques_destroyed,places_of_worship.mosques_damaged,places_of_worship.churches_destroyed
0,10/7/2023,mohtel,24,0,232.0,232.0,232,232,0,0,...,4.0,0.0,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10/8/2023,mohtel,24,0,138.0,370.0,138,370,78,41,...,8.0,0.0,159.0,159.0,NaN,NaN,NaN,NaN,NaN,NaN
2,10/9/2023,mohtel,24,8,190.0,560.0,190,560,91,61,...,12.0,0.0,790.0,790.0,NaN,NaN,NaN,NaN,NaN,NaN
3,10/10/2023,mohtel,24,8,340.0,900.0,340,900,260,230,...,17.0,0.0,1009.0,1009.0,NaN,NaN,NaN,NaN,NaN,NaN
4,10/11/2023,gmotel,24,23,200.0,1100.0,200,1100,398,230,...,21.0,0.0,2835.0,2835.0,27.0,3.0,75.0,10.0,NaN,NaN

In [6]:
df.shape

(967, 39)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 967 entries, 0 to 966
Data columns (total 39 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   report_date                               967 non-null    object
 1   report_source                             967 non-null    object
 2   report_period                             967 non-null    int64
 3   ext_massacres_cum                         967 non-null    int64
 4   killed                                    940 non-null    float64
 5   killed_cum                                960 non-null    float64
 6   ext_killed                                967 non-null    int64
 7   ext_killed_cum                            967 non-null    int64
 8   ext_killed_children_cum                   967 non-null    int64
 9   ext_killed_women_cum                      967 non-null    int64
 10  injured_cum                               952 non-null    float64
 11  ext_injured                               967 non-null    int64
 12  ext_injured_cum                           967 non-null    int64
 13  ext_civdef_killed_cum                     967 non-null    int64
 14  med_killed_cum                            144 non-null    float64
 15  ext_med_killed_cum                        967 non-null    int64
 16  press_killed_cum                          175 non-null    float64
 17  ext_press_killed_cum                      967 non-null    int64
 18  killed_recovered                          244 non-null    float64
 19  killed_succumbed                          37 non-null     float64
 20  killed_truce_new                          399 non-null    float64
 21  child_famine_cum                          315 non-null    float64
 22  famine_cum                                315 non-null    float64
 23  aid_seeker_killed_cum                     350 non-null    float64
 24  aid_seeker_injured_cum                    350 non-null    float64
 25  civic_buildings.ext_destroyed             730 non-null    float64
 26  educational_buildings.ext_destroyed       730 non-null    float64
 27  educational_buildings.ext_damaged         730 non-null    float64
 28  places_of_worship.ext_mosques_destroyed   730 non-null    float64
 29  places_of_worship.ext_mosques_damaged     701 non-null    float64
 30  places_of_worship.ext_churches_destroyed  730 non-null    float64
 31  residential.ext_destroyed                 730 non-null    float64
 32  residential.destroyed                     111 non-null    float64
 33  civic_buildings.destroyed                 87 non-null     float64
 34  educational_buildings.destroyed           94 non-null     float64
 35  educational_buildings.damaged             95 non-null     float64
 36  places_of_worship.mosques_destroyed       86 non-null     float64
 37  places_of_worship.mosques_damaged         70 non-null     float64
 38  places_of_worship.churches_destroyed      88 non-null     float64
dtypes: float64(26), int64(11), object(2)
memory usage: 294.8+ KB

In [10]:
df.describe()

,report_period,ext_massacres_cum,killed,killed_cum,ext_killed,ext_killed_cum,ext_killed_children_cum,ext_killed_women_cum,injured_cum,ext_injured,...,places_of_worship.ext_mosques_damaged,places_of_worship.ext_churches_destroyed,residential.ext_destroyed,residential.destroyed,civic_buildings.destroyed,educational_buildings.destroyed,educational_buildings.damaged,places_of_worship.mosques_destroyed,places_of_worship.mosques_damaged,places_of_worship.churches_destroyed
count,967.000000,967.000000,940.000000,960.000000,967.000000,967.000000,967.000000,967.000000,952.000000,967.000000,...,701.000000,730.000000,730.000000,111.000000,87.000000,94.000000,95.000000,86.000000,70.000000,88.0
mean,23.975181,7444.841779,72.747872,48404.812500,75.427094,48176.414685,16464.692865,10843.122027,115972.449580,178.820062,...,216.646220,2.884932,155675.967123,96203.810811,171.448276,102.723404,302.684211,426.418605,235.157143,3.0
std,10.388689,4520.821845,100.120945,18157.297685,105.572837,18290.700849,4351.093244,2718.873873,43741.090992,273.809648,...,46.710633,0.477669,94854.760887,70840.929385,38.872110,30.622012,55.734794,282.290525,43.384909,0.0
min,0.000000,0.000000,0.000000,232.000000,0.000000,232.000000,0.000000,0.000000,1610.000000,0.000000,...,4.000000,0.000000,80.000000,159.000000,27.000000,3.000000,75.000000,10.000000,145.000000,3.0
25%,24.000000,3260.000000,10.000000,37114.000000,10.000000,36568.000000,15348.000000,10231.000000,85273.500000,15.000000,...,212.000000,3.000000,70000.000000,52250.000000,136.000000,94.250000,295.000000,161.000000,200.000000,3.0
50%,24.000000,10100.000000,45.000000,47546.000000,46.000000,47487.000000,17861.000000,12316.000000,111639.000000,104.000000,...,214.000000,3.000000,150000.000000,70000.000000,184.000000,103.000000,309.000000,245.000000,214.000000,3.0
75%,24.000000,12000.000000,86.250000,66240.750000,88.000000,66122.500000,20000.000000,12500.000000,169468.250000,222.500000,...,214.000000,3.000000,165000.000000,150000.000000,199.500000,121.750000,333.500000,610.750000,266.000000,3.0
max,96.000000,12000.000000,786.000000,72938.000000,828.000000,72938.000000,20179.000000,12500.000000,172919.000000,3652.000000,...,326.000000,3.000000,416000.000000,416000.000000,247.000000,165.000000,392.000000,835.000000,326.000000,3.0

In [12]:
df[df.duplicated()]

Empty DataFrame
Columns: [report_date, report_source, report_period, ext_massacres_cum, killed, killed_cum, ext_killed, ext_killed_cum, ext_killed_children_cum, ext_killed_women_cum, injured_cum, ext_injured, ext_injured_cum, ext_civdef_killed_cum, med_killed_cum, ext_med_killed_cum, press_killed_cum, ext_press_killed_cum, killed_recovered, killed_succumbed, killed_truce_new, child_famine_cum, famine_cum, aid_seeker_killed_cum, aid_seeker_injured_cum, civic_buildings.ext_destroyed, educational_buildings.ext_destroyed, educational_buildings.ext_damaged, places_of_worship.ext_mosques_destroyed, places_of_worship.ext_mosques_damaged, places_of_worship.ext_churches_destroyed, residential.ext_destroyed, residential.destroyed, civic_buildings.destroyed, educational_buildings.destroyed, educational_buildings.damaged, places_of_worship.mosques_destroyed, places_of_worship.mosques_damaged, places_of_worship.churches_destroyed]
Index: []

[0 rows x 39 columns]

## 2.3 Quality Issues

The following potential data quality issues were identified during the assessment phase and will be evaluated during data cleaning:

* The report_date column is stored as an object rather than a datetime data type.
* Several variables contain missing values and require investigation to determine whether they represent reporting gaps or expected omissions.
* Multiple indicators are available in both official and extrapolated forms, requiring clarification regarding their intended use in the analysis.
* Some column names contain hierarchical notation using periods (.), which may affect readability and consistency.
* Certain infrastructure-related variables are only available for a subset of reporting dates and require further assessment.

## 2.4 Tidiness Issues

## 2.5 Cleaning

# 4. Exploratory Data Analysis

## 4.1 Univariate Analysis

## 4.2 Bivariate Analysis

## 4.3 Multivariate Analysis

# 5. Conclusions

# 6. Limitations

# 7. References